# Generated by Django 3.1.1 on 2020-10-13 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Densidad_mamografica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_densidad', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_form', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('habilitado', models.BooleanField(blank=True, max_length=1, null=True)),
                ('completed', models.BooleanField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identidad_etnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidad', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mamografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento_Subformulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuanto', models.CharField(max_length=40, null=True)),
                ('id_medicamento', models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('id_pacient', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Parentezco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_parentezco', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prueba_genetica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prueba_genetica', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terapia_hormonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_terapia', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tiempo_bebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubForm_historia_personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=40, null=True)),
                ('cedula', models.CharField(max_length=40, null=True)),
                ('fecha_de_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=40, null=True)),
                ('identidad_etnica_otro', models.CharField(max_length=40, null=True)),
                ('peso', models.PositiveSmallIntegerField(null=True)),
                ('talla', models.PositiveSmallIntegerField(null=True)),
                ('imc', models.PositiveSmallIntegerField(null=True)),
                ('fuma', models.BooleanField(blank=True, max_length=1, null=True)),
                ('fuma_edad', models.PositiveSmallIntegerField(null=True)),
                ('fuma_actualmente', models.BooleanField(blank=True, max_length=1, null=True)),
                ('fuma_cuanto', models.CharField(max_length=40, null=True)),
                ('bebidas', models.BooleanField(blank=True, max_length=1, null=True)),
                ('bebidas_cuanto_otro', models.CharField(max_length=40, null=True)),
                ('actividad_fisica', models.BooleanField(blank=True, max_length=1, null=True)),
                ('actividad_fisica_cuanto', models.CharField(max_length=40, null=True)),
                ('consume_alimentos_con_grasa', models.BooleanField(blank=True, max_length=1, null=True)),
                ('consume_veg_frut_gram', models.BooleanField(blank=True, max_length=1, null=True)),
                ('diabetes', models.BooleanField(blank=True, max_length=1, null=True)),
                ('diabetes_tipo', models.PositiveSmallIntegerField(null=True)),
                ('radiacion', models.BooleanField(blank=True, max_length=1, null=True)),
                ('bebidas_cuanto', models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.tiempo_bebida')),
                ('identidad_etnica', models.ManyToManyField(default=1, to='main.Identidad_etnica')),
                ('medicamento', models.ManyToManyField(default=1, to='main.Medicamento_Subformulario')),
            ],
        ),
        migrations.CreateModel(
            name='SubForm_historia_familiar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prueba_genetica', models.BooleanField(blank=True, max_length=1, null=True)),
                ('bebidas_cuanto_otro', models.CharField(max_length=40, null=True)),
                ('familiares_mama', models.BooleanField(blank=True, max_length=1, null=True)),
                ('familiares_cancer', models.BooleanField(blank=True, max_length=1, null=True)),
                ('familiares_cancer_tipo', models.CharField(max_length=40, null=True)),
                ('familiares_cancer_parentezco', models.CharField(max_length=40, null=True)),
                ('parentesco', models.ManyToManyField(default=1, to='main.Parentezco')),
                ('prueba_genetica_resultado', models.ManyToManyField(default=1, to='main.Tiempo_bebida')),
            ],
        ),
        migrations.CreateModel(
            name='SubForm_antecedentes_g_o',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manopausa_aplica', models.BooleanField(blank=True, max_length=1, null=True)),
                ('edad_menstruacion', models.PositiveSmallIntegerField(null=True)),
                ('edad_manopausa', models.PositiveSmallIntegerField(null=True)),
                ('parto_aplica', models.BooleanField(blank=True, max_length=1, null=True)),
                ('parto_cantidad', models.PositiveSmallIntegerField(null=True)),
                ('edad_ult_hijo', models.PositiveSmallIntegerField(null=True)),
                ('lactancia_aplica', models.BooleanField(blank=True, max_length=1, null=True)),
                ('lactancia_tiempo', models.PositiveSmallIntegerField(null=True)),
                ('anticonceptivos_aplica', models.BooleanField(blank=True, max_length=1, null=True)),
                ('anticonceptivos_cuanto', models.PositiveSmallIntegerField(null=True)),
                ('anticonceptivos_ult_vez', models.DateField()),
                ('terapia_hormonal_aplica', models.BooleanField(blank=True, max_length=1, null=True)),
                ('terapia_hormonal_tiempo', models.CharField(max_length=40, null=True)),
                ('biopsia_aplica', models.BooleanField(blank=True, max_length=1, null=True)),
                ('biopsia_cuantas', models.PositiveSmallIntegerField(null=True)),
                ('biopsia_resultado', models.CharField(max_length=40, null=True)),
                ('terapia_hormonal_tipo', models.ManyToManyField(default=1, to='main.Terapia_hormonal')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contenido', models.CharField(max_length=500, null=True)),
                ('densidad_mamografica', models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.tiempo_bebida')),
                ('formulario', models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.form')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.clinic')),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='SubForm_antecedentes_g_o',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.subform_antecedentes_g_o'),
        ),
        migrations.AddField(
            model_name='form',
            name='SubForm_historia_familiar',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.subform_historia_familiar'),
        ),
        migrations.AddField(
            model_name='form',
            name='SubForm_historia_personal',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.subform_historia_personal'),
        ),
        migrations.AddField(
            model_name='form',
            name='id_pacient',
            field=models.ManyToManyField(default=1, to='main.Pacient'),
        ),
        migrations.AddField(
            model_name='form',
            name='urls_imgs',
            field=models.ManyToManyField(default=1, to='main.Mamografia'),
        ),
    ]
