# Generated by Django 3.1.1 on 2020-10-16 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subform_historia_familiar',
            name='parentesco',
            field=models.ManyToManyField(to='main.Parentezco'),
        ),
        migrations.AlterField(
            model_name='subform_historia_familiar',
            name='prueba_genetica_resultado',
            field=models.ManyToManyField(to='main.Tiempo_bebida'),
        ),
        migrations.RemoveField(
            model_name='subform_historia_personal',
            name='identidad_etnica',
        ),
        migrations.AddField(
            model_name='subform_historia_personal',
            name='identidad_etnica',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.identidad_etnica'),
        ),
    ]
