# Generated by Django 3.1.1 on 2020-10-26 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subform_antecedentes_g_o',
            name='form',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='subform_ant_g_o', to='main.form'),
        ),
        migrations.AlterField(
            model_name='subform_antecedentes_g_o',
            name='lactancia_tiempo',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_familiar',
            name='form',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='subform_hist_fam', to='main.form'),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='form',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='subform_hist_per', to='main.form'),
        ),
    ]
