# Generated by Django 3.1.1 on 2021-01-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subform_historia_familiar',
            name='parentesco',
        ),
        migrations.AddField(
            model_name='subform_historia_familiar',
            name='parentesco',
            field=models.ManyToManyField(blank=True, to='main.Parentesco'),
        ),
        migrations.RemoveField(
            model_name='subform_historia_familiar',
            name='prueba_genetica_resultado',
        ),
        migrations.AddField(
            model_name='subform_historia_familiar',
            name='prueba_genetica_resultado',
            field=models.ManyToManyField(blank=True, to='main.Prueba_genetica'),
        ),
    ]
