# Generated by Django 3.1.1 on 2020-10-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201016_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='id_pacient',
            field=models.ManyToManyField(to='main.Pacient'),
        ),
        migrations.AlterField(
            model_name='form',
            name='urls_imgs',
            field=models.ManyToManyField(to='main.Mamografia'),
        ),
        migrations.AlterField(
            model_name='subform_antecedentes_g_o',
            name='terapia_hormonal_tipo',
            field=models.ManyToManyField(to='main.Terapia_hormonal'),
        ),
        migrations.AlterField(
            model_name='subform_historia_familiar',
            name='bebidas_cuanto_otro',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='medicamento',
            field=models.ManyToManyField(to='main.Medicamento_Subformulario'),
        ),
    ]
