# Generated by Django 3.1.1 on 2020-10-26 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201025_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='identidad_etnica',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.identidad_etnica'),
        ),
    ]
