# Generated by Django 3.1.1 on 2020-10-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201016_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar_cancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiares_cancer_tipo', models.CharField(max_length=40, null=True)),
                ('familiares_cancer_parentezco', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Parentezco',
            new_name='Parentesco',
        ),
        migrations.RenameField(
            model_name='parentesco',
            old_name='tipo_parentezco',
            new_name='tipo_parentesco',
        ),
        migrations.RemoveField(
            model_name='subform_historia_familiar',
            name='familiares_cancer_parentezco',
        ),
        migrations.RemoveField(
            model_name='subform_historia_familiar',
            name='familiares_cancer_tipo',
        ),
        migrations.AddField(
            model_name='subform_historia_familiar',
            name='parentesco_tipo',
            field=models.ManyToManyField(to='main.Familiar_cancer'),
        ),
    ]
