# Generated by Django 3.1.1 on 2020-10-16 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201016_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Densidad_mamografica',
        ),
    ]
