# Generated by Django 3.1.1 on 2021-01-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210112_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subform_antecedentes_g_o',
            name='terapia',
            field=models.CharField(choices=[(0, 'No sabe'), (1, 'Sistémico (Oral)'), (2, 'Tópico (Crema o Parche)'), (3, 'Intravaginal (Óvulos o Anillo)')], default=0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='bebidas_cuanto',
            field=models.CharField(choices=[(0, 'Más de tres a la semana'), (1, 'Más de dos al día'), (2, 'Otro')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='clinic',
            field=models.CharField(choices=[(0, 'Max Peralta'), (1, 'San Juan De Dios')], default=0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='diabetes',
            field=models.CharField(choices=[(0, 'Tipo 1'), (1, 'Tipo 2'), (2, 'Ninguna')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='identidad_etnica',
            field=models.CharField(choices=[(0, 'Indígena'), (1, 'Afrodescendiente'), (2, 'Origen asiático'), (3, 'Mulata'), (4, 'Mestiza'), (5, 'Blanca'), (6, 'No sabe')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='nacionalidad',
            field=models.CharField(blank=True, choices=[(0, 'Afganistán'), (1, 'Albania'), (2, 'Alemania'), (3, 'Andorra'), (4, 'Angola'), (5, 'Anguila'), (6, 'Antártida'), (7, 'Antigua y Barbuda'), (8, 'Arabia Saudita'), (9, 'Argelia'), (10, 'Argentina'), (11, 'Armenia'), (12, 'Aruba'), (13, 'Australia'), (14, 'Austria'), (15, 'Azerbaiyán'), (16, 'Bélgica'), (17, 'Bahamas'), (18, 'Bahrein'), (19, 'Bangladesh'), (20, 'Barbados'), (21, 'Belice'), (22, 'Benín'), (23, 'Bhután'), (24, 'Bielorrusia'), (25, 'Birmania'), (26, 'Bolivia'), (27, 'Bosnia y Herzegovina'), (28, 'Botsuana'), (29, 'Brasil'), (30, 'Brunéi'), (31, 'Bulgaria'), (32, 'Burkina Faso'), (33, 'Burundi'), (34, 'Cabo Verde'), (35, 'Camboya'), (36, 'Camerún'), (37, 'Canadá'), (38, 'Chad'), (39, 'Chile'), (40, 'China'), (41, 'Chipre'), (42, 'Ciudad del Vaticano'), (43, 'Colombia'), (44, 'Comoras'), (45, 'República del Congo'), (46, 'República Democrática del Congo'), (47, 'Corea del Norte'), (48, 'Corea del Sur'), (49, 'Costa de Marfil'), (50, 'Costa Rica'), (51, 'Croacia'), (52, 'Cuba'), (53, 'Curazao'), (54, 'Dinamarca'), (55, 'Dominica'), (56, 'Ecuador'), (57, 'Egipto'), (58, 'El Salvador'), (59, 'Emiratos Árabes Unidos'), (60, 'Eritrea'), (61, 'Eslovaquia'), (62, 'Eslovenia'), (63, 'España'), (64, 'Estados Unidos de América'), (65, 'Estonia'), (66, 'Etiopía'), (67, 'Filipinas'), (68, 'Finlandia'), (69, 'Fiyi'), (70, 'Francia'), (71, 'Gabón'), (72, 'Gambia'), (73, 'Georgia'), (74, 'Ghana'), (75, 'Gibraltar'), (76, 'Granada'), (77, 'Grecia'), (78, 'Groenlandia'), (79, 'Guadalupe'), (80, 'Guam'), (81, 'Guatemala'), (82, 'Guayana Francesa'), (83, 'Guernsey'), (84, 'Guinea'), (85, 'Guinea Ecuatorial'), (86, 'Guinea-Bissau'), (87, 'Guyana'), (88, 'Haití'), (89, 'Honduras'), (90, 'Hong kong'), (91, 'Hungría'), (92, 'India'), (93, 'Indonesia'), (94, 'Irán'), (95, 'Irak'), (96, 'Irlanda'), (97, 'Isla Bouvet'), (98, 'Isla de Man'), (99, 'Isla de Navidad'), (100, 'Isla Norfolk'), (101, 'Islandia'), (102, 'Islas Bermudas'), (103, 'Islas Caimán'), (104, 'Islas Cocos (Keeling)'), (105, 'Islas Cook'), (106, 'Islas de Åland'), (107, 'Islas Feroe'), (108, 'Islas Georgias del Sur y Sandwich del Sur'), (109, 'Islas Heard y McDonald'), (110, 'Islas Maldivas'), (111, 'Islas Malvinas'), (112, 'Islas Marianas del Norte'), (113, 'Islas Marshall'), (114, 'Islas Pitcairn'), (115, 'Islas Salomón'), (116, 'Islas Turcas y Caicos'), (117, 'Islas Ultramarinas Menores de Estados Unidos'), (118, 'Islas Vírgenes Británicas'), (119, 'Islas Vírgenes de los Estados Unidos'), (120, 'Israel'), (121, 'Italia'), (122, 'Jamaica'), (123, 'Japón'), (124, 'Jersey'), (125, 'Jordania'), (126, 'Kazajistán'), (127, 'Kenia'), (128, 'Kirguistán'), (129, 'Kiribati'), (130, 'Kuwait'), (131, 'Líbano'), (132, 'Laos'), (133, 'Lesoto'), (134, 'Letonia'), (135, 'Liberia'), (136, 'Libia'), (137, 'Liechtenstein'), (138, 'Lituania'), (139, 'Luxemburgo'), (140, 'México'), (141, 'Mónaco'), (142, 'Macao'), (143, 'Macedônia'), (144, 'Madagascar'), (145, 'Malasia'), (146, 'Malawi'), (147, 'Mali'), (148, 'Malta'), (149, 'Marruecos'), (150, 'Martinica'), (151, 'Mauricio'), (152, 'Mauritania'), (153, 'Mayotte'), (154, 'Micronesia'), (155, 'Moldavia'), (156, 'Mongolia'), (157, 'Montenegro'), (158, 'Montserrat'), (159, 'Mozambique'), (160, 'Namibia'), (161, 'Nauru'), (162, 'Nepal'), (163, 'Nicaragua'), (164, 'Niger'), (165, 'Nigeria'), (166, 'Niue'), (167, 'Noruega'), (168, 'Nueva Caledonia'), (169, 'Nueva Zelanda'), (170, 'Omán'), (171, 'Países Bajos'), (172, 'Pakistán'), (173, 'Palau'), (174, 'Palestina'), (175, 'Panamá'), (176, 'Papúa Nueva Guinea'), (177, 'Paraguay'), (178, 'Perú'), (179, 'Polinesia Francesa'), (180, 'Polonia'), (181, 'Portugal'), (182, 'Puerto Rico'), (183, 'Qatar'), (184, 'Reino Unido'), (185, 'República Centroafricana'), (186, 'República Checa'), (187, 'República Dominicana'), (188, 'República de Sudán del Sur'), (189, 'Reunión'), (190, 'Ruanda'), (191, 'Rumanía'), (192, 'Rusia'), (193, 'Sahara Occidental'), (194, 'Samoa'), (195, 'Samoa Americana'), (196, 'San Bartolomé'), (197, 'San Cristóbal y Nieves'), (198, 'San Marino'), (199, 'San Martín (Francia)'), (200, 'San Pedro y Miquelón'), (201, 'San Vicente y las Granadinas'), (202, 'Santa Elena'), (203, 'Santa Lucía'), (204, 'Santo Tomé y Príncipe'), (205, 'Senegal'), (206, 'Serbia'), (207, 'Seychelles'), (208, 'Sierra Leona'), (209, 'Singapur'), (210, 'Sint Maarten'), (211, 'Siria'), (212, 'Somalia'), (213, 'Sri lanka'), (214, 'Sudáfrica'), (215, 'Sudán'), (216, 'Suecia'), (217, 'Suiza'), (218, 'Surinám'), (219, 'Svalbard y Jan Mayen'), (220, 'Swazilandia'), (221, 'Tayikistán'), (222, 'Tailandia'), (223, 'Taiwán'), (224, 'Tanzania'), (225, 'Territorio Británico del Océano Índico'), (226, 'Territorios Australes y Antárticas Franceses'), (227, 'Timor Oriental'), (228, 'Togo'), (229, 'Tokelau'), (230, 'Tonga'), (231, 'Trinidad y Tobago'), (232, 'Tunez'), (233, 'Turkmenistán'), (234, 'Turquía'), (235, 'Tuvalu'), (236, 'Ucrania'), (237, 'Uganda'), (238, 'Uruguay'), (239, 'Uzbekistán'), (240, 'Vanuatu'), (241, 'Venezuela'), (242, 'Vietnam'), (243, 'Wallis y Futuna'), (244, 'Yemen'), (245, 'Yibuti'), (246, 'Zambia'), (247, 'Zimbabue')], default=0, max_length=2, null=True),
        ),
    ]
