# Generated by Django 3.1.1 on 2021-01-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210112_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='clinic',
            field=models.CharField(choices=[(0, 'Max Peralta'), (1, 'San Juan De Dios')], default=1, max_length=5, null=True),
        ),
    ]
