# Generated by Django 3.1.1 on 2020-10-21 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201020_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='clinic',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.clinic'),
        ),
    ]
