# Generated by Django 3.1.1 on 2020-10-21 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201020_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='clinic',
        ),
    ]
