# Generated by Django 3.1.1 on 2020-11-07 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201105_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='urls_imgs',
        ),
        migrations.AddField(
            model_name='mamografia',
            name='form',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='main.form'),
        ),
    ]
