# Generated by Django 3.1.1 on 2021-01-12 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210112_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='identidad_etnica',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.identidad_etnica'),
        ),
    ]
