# Generated by Django 3.1.1 on 2020-10-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_profile_clinic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='SubForm_antecedentes_g_o',
            new_name='subForm_antecedentes_g_o',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='SubForm_historia_familiar',
            new_name='subForm_historia_familiar',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='SubForm_historia_personal',
            new_name='subForm_historia_personal',
        ),
    ]
