# Generated by Django 3.1.1 on 2021-01-12 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210112_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='clinic',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.clinic'),
        ),
    ]
