# Generated by Django 3.1.1 on 2020-10-21 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_profile_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='clinic',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.clinic'),
        ),
    ]
