# Generated by Django 3.1.1 on 2020-11-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_mamografia_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='imc',
            field=models.FloatField(null=True),
        ),
    ]
