# Generated by Django 3.1.1 on 2020-10-21 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201021_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.clinic'),
        ),
    ]
