# Generated by Django 3.1.1 on 2021-01-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201115_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subform_historia_personal',
            old_name='radiacion',
            new_name='tratamiento_torax',
        ),
    ]
