# Generated by Django 3.1.1 on 2021-01-11 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210111_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='actividad_fisica_cuanto',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='bebidas_cuanto',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='bebidas_cuanto_otro',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='cedula',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='clinic',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.clinic'),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='cuanto_anastrozol',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='cuanto_aspirina',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='cuanto_bifosfonatos',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='cuanto_metformina',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='cuanto_tamoxifeno',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='diabetes',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='fuma_cuanto',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='fuma_edad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='identidad_etnica',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.identidad_etnica'),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='identidad_etnica_otro',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='imc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='nombre',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='peso',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='talla',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
