# Generated by Django 3.1.1 on 2020-10-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201021_1431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pacient',
            new_name='Patient',
        ),
        migrations.RemoveField(
            model_name='form',
            name='id_pacient',
        ),
        migrations.AddField(
            model_name='form',
            name='id_Patient',
            field=models.ManyToManyField(to='main.Patient'),
        ),
    ]
