# Generated by Django 3.1.1 on 2020-10-21 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201021_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='id_pacient',
            new_name='id_patient',
        ),
    ]
