# Generated by Django 3.1.1 on 2021-01-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210111_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subform_antecedentes_g_o',
            old_name='manopausia_aplica',
            new_name='menopausia_aplica',
        ),
    ]
