# Generated by Django 3.1.1 on 2020-10-21 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201021_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='id_Patient',
        ),
        migrations.AddField(
            model_name='form',
            name='id_Patient',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.patient'),
        ),
    ]
