# Generated by Django 3.1.1 on 2020-10-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201021_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='id_Patient',
            new_name='id_patient',
        ),
    ]
