# Generated by Django 3.1.1 on 2021-01-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210111_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentesco',
            name='tipo_parentesco',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='prueba_genetica',
            name='tipo_prueba_genetica',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_antecedentes_g_o',
            name='anticonceptivos_cuanto',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_antecedentes_g_o',
            name='anticonceptivos_ult_vez',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_antecedentes_g_o',
            name='biopsia_cuantas',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subform_antecedentes_g_o',
            name='biopsia_resultado',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_antecedentes_g_o',
            name='cuanto_tiempo_terapia',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_antecedentes_g_o',
            name='edad_menopausia',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subform_antecedentes_g_o',
            name='edad_menstruacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subform_antecedentes_g_o',
            name='edad_ult_hijo',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subform_antecedentes_g_o',
            name='lactancia_tiempo',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_antecedentes_g_o',
            name='parto_cantidad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_familiar',
            name='familiares_cancer_parentesco',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_familiar',
            name='familiares_cancer_tipo',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_familiar',
            name='parentesco',
            field=models.ManyToManyField(blank=True, to='main.Parentesco'),
        ),
        migrations.AlterField(
            model_name='subform_historia_familiar',
            name='prueba_genetica_otro',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_familiar',
            name='prueba_genetica_resultado',
            field=models.ManyToManyField(blank=True, to='main.Prueba_genetica'),
        ),
    ]
