# Generated by Django 3.1.1 on 2020-10-22 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201021_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='subForm_antecedentes_g_o',
        ),
        migrations.RemoveField(
            model_name='form',
            name='subForm_historia_familiar',
        ),
        migrations.RemoveField(
            model_name='form',
            name='subForm_historia_personal',
        ),
        migrations.AddField(
            model_name='subform_antecedentes_g_o',
            name='form_id',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.form'),
        ),
        migrations.AddField(
            model_name='subform_historia_familiar',
            name='form_id',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.form'),
        ),
        migrations.AddField(
            model_name='subform_historia_personal',
            name='form_id',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.form'),
        ),
    ]
