# Generated by Django 3.1.1 on 2020-10-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201021_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='acronym',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
