# Generated by Django 3.1.1 on 2020-10-22 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_clinic_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subform_antecedentes_g_o',
            name='form_id',
            field=models.OneToOneField(default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.form'),
        ),
        migrations.AlterField(
            model_name='subform_historia_familiar',
            name='form_id',
            field=models.OneToOneField(default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.form'),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='form_id',
            field=models.OneToOneField(default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.form'),
        ),
    ]
