# Generated by Django 3.1.1 on 2020-10-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20201021_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subform_antecedentes_g_o',
            name='anticonceptivos_ult_vez',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='fecha_de_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
