# Generated by Django 3.1.1 on 2020-10-22 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201021_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subform_historia_familiar',
            name='form_id',
        ),
        migrations.AddField(
            model_name='subform_historia_familiar',
            name='familiares_cancer_parentezco',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='subform_historia_familiar',
            name='familiares_cancer_tipo',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='bebidas_cuanto',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.tiempo_bebida'),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='identidad_etnica',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.identidad_etnica'),
        ),
    ]
