# Generated by Django 3.1.1 on 2020-10-22 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20201021_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='bebidas_cuanto',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.tiempo_bebida'),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='identidad_etnica',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.identidad_etnica'),
        ),
    ]
