# Generated by Django 3.1.1 on 2020-10-22 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20201022_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='bebidas_cuanto',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.tiempo_bebida'),
        ),
    ]
