# Generated by Django 3.1.1 on 2020-10-22 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20201022_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='subform_historia_familiar',
            name='form_id',
            field=models.OneToOneField(default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.form'),
        ),
    ]
