# Generated by Django 3.1.1 on 2020-10-22 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_subform_historia_familiar_form_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subform_antecedentes_g_o',
            name='form_id',
        ),
        migrations.RemoveField(
            model_name='subform_historia_familiar',
            name='form_id',
        ),
        migrations.RemoveField(
            model_name='subform_historia_personal',
            name='form_id',
        ),
        migrations.AddField(
            model_name='form',
            name='subform_ant_g_o',
            field=models.OneToOneField(default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.subform_antecedentes_g_o'),
        ),
        migrations.AddField(
            model_name='form',
            name='subform_hist_fam',
            field=models.OneToOneField(default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.subform_historia_familiar'),
        ),
        migrations.AddField(
            model_name='form',
            name='subform_hist_per',
            field=models.OneToOneField(default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.subform_historia_personal'),
        ),
    ]
