# Generated by Django 3.1.1 on 2020-10-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20201022_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='submitted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
