# Generated by Django 3.1.1 on 2020-10-23 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20201022_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento_subformulario',
            name='id_medicamento',
        ),
        migrations.RemoveField(
            model_name='report',
            name='densidad_mamografica',
        ),
        migrations.RemoveField(
            model_name='subform_historia_personal',
            name='diabetes_tipo',
        ),
        migrations.RemoveField(
            model_name='subform_historia_personal',
            name='medicamento',
        ),
        migrations.AddField(
            model_name='subform_historia_personal',
            name='clinic',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.clinic'),
        ),
        migrations.AddField(
            model_name='subform_historia_personal',
            name='cuanto_anastrozol',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='subform_historia_personal',
            name='cuanto_aspirina',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='subform_historia_personal',
            name='cuanto_bifosfonatos',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='subform_historia_personal',
            name='cuanto_metformina',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='subform_historia_personal',
            name='cuanto_tamoxifeno',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='subform_historia_personal',
            name='id_medicamento_anastrozol',
            field=models.BooleanField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='subform_historia_personal',
            name='id_medicamento_aspirina',
            field=models.BooleanField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='subform_historia_personal',
            name='id_medicamento_bifosfonatos',
            field=models.BooleanField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='subform_historia_personal',
            name='id_medicamento_metformina',
            field=models.BooleanField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='subform_historia_personal',
            name='id_medicamento_tamoxifeno',
            field=models.BooleanField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_familiar',
            name='prueba_genetica_resultado',
            field=models.ManyToManyField(to='main.Prueba_genetica'),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='bebidas_cuanto',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subform_historia_personal',
            name='diabetes',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='Medicamento',
        ),
        migrations.DeleteModel(
            name='Medicamento_Subformulario',
        ),
        migrations.DeleteModel(
            name='Tiempo_bebida',
        ),
    ]
