# Generated by Django 3.1.1 on 2020-10-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20201023_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subform_antecedentes_g_o',
            old_name='terapia_hormonal_tiempo',
            new_name='cuanto_tiempo_intravaginal',
        ),
        migrations.AddField(
            model_name='subform_antecedentes_g_o',
            name='cuanto_tiempo_nosabe',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='subform_antecedentes_g_o',
            name='cuanto_tiempo_topico',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
