# Generated by Django 3.1.1 on 2020-10-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20201023_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subform_historia_personal',
            old_name='id_medicamento_anastrozol',
            new_name='toma_medicamento_anastrozol',
        ),
        migrations.RenameField(
            model_name='subform_historia_personal',
            old_name='id_medicamento_aspirina',
            new_name='toma_medicamento_aspirina',
        ),
        migrations.RenameField(
            model_name='subform_historia_personal',
            old_name='id_medicamento_bifosfonatos',
            new_name='toma_medicamento_bifosfonatos',
        ),
        migrations.RenameField(
            model_name='subform_historia_personal',
            old_name='id_medicamento_metformina',
            new_name='toma_medicamento_metformina',
        ),
        migrations.RenameField(
            model_name='subform_historia_personal',
            old_name='id_medicamento_tamoxifeno',
            new_name='toma_medicamento_tamoxifeno',
        ),
        migrations.RemoveField(
            model_name='subform_historia_familiar',
            name='parentesco_tipo',
        ),
        migrations.DeleteModel(
            name='Familiar_cancer',
        ),
    ]
