# Generated by Django 3.1.1 on 2020-10-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20201023_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subform_antecedentes_g_o',
            old_name='cuanto_tiempo_intravaginal',
            new_name='cuanto_tiempo_terapia',
        ),
        migrations.RemoveField(
            model_name='subform_antecedentes_g_o',
            name='cuanto_tiempo_nosabe',
        ),
        migrations.RemoveField(
            model_name='subform_antecedentes_g_o',
            name='cuanto_tiempo_sistemico',
        ),
        migrations.RemoveField(
            model_name='subform_antecedentes_g_o',
            name='cuanto_tiempo_topico',
        ),
        migrations.RemoveField(
            model_name='subform_antecedentes_g_o',
            name='terapia_hormonal_intravaginal',
        ),
        migrations.RemoveField(
            model_name='subform_antecedentes_g_o',
            name='terapia_hormonal_nosabe',
        ),
        migrations.RemoveField(
            model_name='subform_antecedentes_g_o',
            name='terapia_hormonal_sistemico',
        ),
        migrations.RemoveField(
            model_name='subform_antecedentes_g_o',
            name='terapia_hormonal_topico',
        ),
        migrations.AddField(
            model_name='subform_antecedentes_g_o',
            name='terapia',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
