# Generated by Django 3.1.1 on 2020-10-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20201023_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subform_antecedentes_g_o',
            name='anticonceptivos_cuanto',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
