# Generated by Django 3.1.1 on 2020-10-24 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20201023_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subform_historia_familiar',
            old_name='bebidas_cuanto_otro',
            new_name='prueba_genetica_otro',
        ),
    ]
