# Generated by Django 3.1.1 on 2020-10-24 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20201023_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subform_historia_familiar',
            old_name='familiares_cancer_parentezco',
            new_name='familiares_cancer_parentesco',
        ),
    ]
